allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  # Renovate security update: svelte@5.53.5
  - svelte@5.53.5
  # Renovate security update: vite@8.0.5
  - vite@8.0.5
